In [1]:
# importar bibliotecas necesarias

import pandas as pd
import numpy as np
from datetime import date
import sqlalchemy as sql

In [2]:
engine = sql.create_engine("mysql://mysql:reportserver@34.74.68.92:3306/BIServer")

In [3]:
fecha_inicio = input("Por favor inserte la fecha en formato aaaa-mm-dd")

Por favor inserte la fecha en formato aaaa-mm-dd2021-01-15

In [4]:
fecha_fin = input("Por favor inserte la fecha en formato aaaa-mm-dd")

Por favor inserte la fecha en formato aaaa-mm-dd2021-01-20

In [ ]:
sql_data = pd.read_sql_query(f"SELECT Agencia_movimiento, Cliente, Cedula, Producto, Nro_Cuenta, Canal, Fecha_Movimiento, Monto_Movimiento, Saldo_Final FROM vw_rs_depositos_movimiento WHERE (Producto = 'APORTES ORDINARIOS' OR Producto = 'PLAN APORTES MENSUAL') AND (Fecha_Movimiento BETWEEN '{fecha_inicio}' AND '{fecha_fin}') AND (Canal <> 'Capitalización Aportes' AND Monto_Movimiento > 80000)",engine)

In [78]:
sql_data

,Agencia_Movimiento,Cliente,Cedula,Producto,Nro_Cuenta,Canal,Fecha_Movimiento,Monto_Movimiento,Saldo_Final
0,TULUA,MARIA BLANCA LOPEZ SANTA,29757187,APORTES ORDINARIOS,04400000000021629,Caja,2021-01-15,753000.0,1420579.36
1,BUGA,JOHN JAIRO OBANDO LAME,94419562,APORTES ORDINARIOS,01400000000002160,Caja,2021-01-15,220000.0,537358.79
2,ARMENIA,HUGO HUMBERTO MUNEVAR IBAGON,17192744,APORTES ORDINARIOS,01400000000018326,Caja,2021-01-15,207000.0,260720.17
3,ARMENIA,HUGO HUMBERTO MUNEVAR IBAGON,17192744,APORTES ORDINARIOS,01400000000018326,Traslados Internos,2021-01-15,140000.0,400720.17
4,ARMENIA,MARIANA GIL MEDINA,1091886885,APORTES ORDINARIOS,01400001091886885,Traslados Internos,2021-01-15,150000.0,204234.11
...,...,...,...,...,...,...,...,...,...
106,FUNDADORES,KAREN SOFIA PENCUA LOPEZ,1094905486,PLAN APORTES MENSUAL,08409000001006408,Caja,2021-01-20,100000.0,160000.00
107,QUIMBAYA,JAHN MILIANA GARCES MEDINA,29815056,PLAN APORTES MENSUAL,05409000001007868,Caja,2021-01-20,100000.0,100000.00
108,QUIMBAYA,RIGOBERTO DE JESUS GARCIA PAREJA,6465466,PLAN APORTES MENSUAL,05409000001007869,Caja,2021-01-20,100000.0,100000.00
109,QUIMBAYA,LUZ ALEYDA PINEDA FLOREZ,24808877,APORTES ORDINARIOS,01400000000004320,Caja,2021-01-20,1850100.0,1955150.51
110,TEBAIDA,LUIS FERNANDO JIMENEZ QUITIAN,1101020179,APORTES ORDINARIOS,09400000000024355,Traslados Internos,2021-01-20,560000.0,613295.00

In [86]:
cartera = pd.read_sql_query(f"SELECT Fecha_Desembolso, Identificación_Asociado FROM vw_rs_cartera_x_edades WHERE Fecha_Desembolso BETWEEN '{fecha_inicio}' AND '{fecha_fin}'",engine)

In [87]:
cartera

    Fecha_Desembolso Identificación_Asociado
0         2021-01-15                80226688
1         2021-01-15                29757187
2         2021-01-15              1094898784
3         2021-01-15                 4551469
4         2021-01-15                93062029
..               ...                     ...
133       2021-01-20                14880454
134       2021-01-20              1101020179
135       2021-01-20                24808877
136       2021-01-20              1094963126
137       2021-01-20                16365642

[138 rows x 2 columns]

In [88]:
cruce_1 = sql_data.merge(cartera,how ='left',left_on='Cedula', right_on='Identificación_Asociado')

In [97]:
cruce_1

,Agencia_Movimiento,Cliente,Cedula,Producto,Nro_Cuenta,Canal,Fecha_Movimiento,Monto_Movimiento,Saldo_Final,Fecha_Desembolso,Identificación_Asociado,Redmine
0,TULUA,MARIA BLANCA LOPEZ SANTA,29757187,APORTES ORDINARIOS,04400000000021629,Caja,2021-01-15,753000.0,1420579.36,2021-01-15,29757187,No hay observacion
1,BUGA,JOHN JAIRO OBANDO LAME,94419562,APORTES ORDINARIOS,01400000000002160,Caja,2021-01-15,220000.0,537358.79,2021-01-15,94419562,No hay observacion
2,ARMENIA,HUGO HUMBERTO MUNEVAR IBAGON,17192744,APORTES ORDINARIOS,01400000000018326,Caja,2021-01-15,207000.0,260720.17,NaN,NaN,Favor reportar consignacion a aportes de 17192...
3,ARMENIA,HUGO HUMBERTO MUNEVAR IBAGON,17192744,APORTES ORDINARIOS,01400000000018326,Traslados Internos,2021-01-15,140000.0,400720.17,NaN,NaN,Favor reportar consignacion a aportes de 17192...
4,ARMENIA,MARIANA GIL MEDINA,1091886885,APORTES ORDINARIOS,01400001091886885,Traslados Internos,2021-01-15,150000.0,204234.11,NaN,NaN,Favor reportar consignacion a aportes de 10918...
...,...,...,...,...,...,...,...,...,...,...,...,...
109,FUNDADORES,KAREN SOFIA PENCUA LOPEZ,1094905486,PLAN APORTES MENSUAL,08409000001006408,Caja,2021-01-20,100000.0,160000.00,NaN,NaN,Favor reportar consignacion a aportes de 10949...
110,QUIMBAYA,JAHN MILIANA GARCES MEDINA,29815056,PLAN APORTES MENSUAL,05409000001007868,Caja,2021-01-20,100000.0,100000.00,NaN,NaN,Favor reportar consignacion a aportes de 29815...
111,QUIMBAYA,RIGOBERTO DE JESUS GARCIA PAREJA,6465466,PLAN APORTES MENSUAL,05409000001007869,Caja,2021-01-20,100000.0,100000.00,NaN,NaN,Favor reportar consignacion a aportes de 64654...
112,QUIMBAYA,LUZ ALEYDA PINEDA FLOREZ,24808877,APORTES ORDINARIOS,01400000000004320,Caja,2021-01-20,1850100.0,1955150.51,2021-01-20,24808877,No hay observacion
113,TEBAIDA,LUIS FERNANDO JIMENEZ QUITIAN,1101020179,APORTES ORDINARIOS,09400000000024355,Traslados Internos,2021-01-20,560000.0,613295.00,2021-01-20,1101020179,No hay observacion

In [98]:
for i in cruce_1.index:
    if pd.isna(cruce_1.loc[i,'Fecha_Desembolso']):
        Monto = cruce_1.loc[i, 'Monto_Movimiento']
        Client = cruce_1.loc[i, 'Cliente']
        Cc = cruce_1.loc[i, 'Cedula']
        Fecha = cruce_1.loc[i, 'Fecha_Movimiento']
        Canal = cruce_1.loc[i, 'Canal']
        cruce_1.loc[i, 'Redmine'] = ('Favor reportar consignacion a aportes de {0} - {1} por {2} realizada el {3} por {4}'.format(Cc, Client, Monto, Fecha, Canal))
    else: 
        cruce_1.drop(cruce_1.loc[i])

KeyError: "['No hay observacion'] not found in axis"

In [95]:
cruce_1

,Agencia_Movimiento,Cliente,Cedula,Producto,Nro_Cuenta,Canal,Fecha_Movimiento,Monto_Movimiento,Saldo_Final,Fecha_Desembolso,Identificación_Asociado,Redmine
0,TULUA,MARIA BLANCA LOPEZ SANTA,29757187,APORTES ORDINARIOS,04400000000021629,Caja,2021-01-15,753000.0,1420579.36,2021-01-15,29757187,No hay observacion
1,BUGA,JOHN JAIRO OBANDO LAME,94419562,APORTES ORDINARIOS,01400000000002160,Caja,2021-01-15,220000.0,537358.79,2021-01-15,94419562,No hay observacion
2,ARMENIA,HUGO HUMBERTO MUNEVAR IBAGON,17192744,APORTES ORDINARIOS,01400000000018326,Caja,2021-01-15,207000.0,260720.17,NaN,NaN,Favor reportar consignacion a aportes de 17192...
3,ARMENIA,HUGO HUMBERTO MUNEVAR IBAGON,17192744,APORTES ORDINARIOS,01400000000018326,Traslados Internos,2021-01-15,140000.0,400720.17,NaN,NaN,Favor reportar consignacion a aportes de 17192...
4,ARMENIA,MARIANA GIL MEDINA,1091886885,APORTES ORDINARIOS,01400001091886885,Traslados Internos,2021-01-15,150000.0,204234.11,NaN,NaN,Favor reportar consignacion a aportes de 10918...
...,...,...,...,...,...,...,...,...,...,...,...,...
109,FUNDADORES,KAREN SOFIA PENCUA LOPEZ,1094905486,PLAN APORTES MENSUAL,08409000001006408,Caja,2021-01-20,100000.0,160000.00,NaN,NaN,Favor reportar consignacion a aportes de 10949...
110,QUIMBAYA,JAHN MILIANA GARCES MEDINA,29815056,PLAN APORTES MENSUAL,05409000001007868,Caja,2021-01-20,100000.0,100000.00,NaN,NaN,Favor reportar consignacion a aportes de 29815...
111,QUIMBAYA,RIGOBERTO DE JESUS GARCIA PAREJA,6465466,PLAN APORTES MENSUAL,05409000001007869,Caja,2021-01-20,100000.0,100000.00,NaN,NaN,Favor reportar consignacion a aportes de 64654...
112,QUIMBAYA,LUZ ALEYDA PINEDA FLOREZ,24808877,APORTES ORDINARIOS,01400000000004320,Caja,2021-01-20,1850100.0,1955150.51,2021-01-20,24808877,No hay observacion
113,TEBAIDA,LUIS FERNANDO JIMENEZ QUITIAN,1101020179,APORTES ORDINARIOS,09400000000024355,Traslados Internos,2021-01-20,560000.0,613295.00,2021-01-20,1101020179,No hay observacion