In [2]:
import pandas as pd 
import sqlalchemy as sql

In [8]:
reporte_sistema = pd.read_excel('C:/Users/analista4operaciones/Desktop/Garantias comunitarias/febrero/reporte_febrero.xls', headers = None)

In [9]:
reporte_sistema.columns

Index(['Nro. Credito', 'Convenio', 'Linea de Credito', 'Nombre de la Entidad',
       'Nit de la Entidad', 'Sucursal', 'Mes de reporte', 'Nombre Cliente',
       'Apellidos Cliente', 'Nit cc', 'Sucursal de desembolso',
       'Telefono Cliente', 'Direccion', 'Ciudad', 'Departamento', 'Celular',
       'Nro pagare', 'Valor del credito', 'Destino del credito', 'Cuota',
       'Plazo', 'Fecha de desembolso', 'Fecha vencimiento', 'Email',
       'Periodo Gracia', 'Amortizacion capital', 'Amortizacion periodo',
       'Amortizacion Modalidad', 'Tasa interes', 'Porcentaje Comision',
       'Modalidad comision', 'Tipo de comision', 'Valor Comision',
       'Valor IVA comision', 'Valor Total Comision', 'Especificacion garantia',
       'Garantia Adicional Nombre Cliente', 'GA Apellidos', 'GA Nit o CC',
       'GA Sucursal', 'GA Telefono', 'GA Direccion', 'GA Ciudad',
       'GA Departamento', 'Observaciones'],
      dtype='object')

In [5]:
#Conexion con la base de datos 
engine = sql.create_engine("mysql://mysql:reportserver@34.74.68.92:3306/BIServer") #Credenciales BD
datos_personales = pd.read_sql_query("select coalesce(`tipo_id`.`name`,'') AS `Tipo_Identificacion`,coalesce(`cliente`.`identification`,'') AS `Nro_Identificacion`,(case when (`cliente`.`legaltype` = '02') then '' when (`cliente`.`legaltype` = '01') then coalesce(`genero`.`description`,'') end) AS `Genero`,coalesce(`cliente`.`borndate`,'0001-01-01') AS `Fecha_Nacimiento`,(year(curdate()) - year(`cliente`.`borndate`)) AS `Edad`,coalesce(`cu_fn_residencia`(`cliente`.`cu_customermaster_id`,2,1000478),'') AS `Telefono_Residencia`,coalesce(`cu_fn_residencia`(`cliente`.`cu_customermaster_id`,4,1000478),'') AS `Codigo_CIIUU_Ciudad_Residencia`,coalesce(`cu_fn_residencia`(`cliente`.`cu_customermaster_id`,4,1001709),'') AS `Codigo_CIIUU_Ciudad_Comercial`,coalesce(`economia`.`codechar`,0) AS `Codigo_CIIU_Asociado` from (((((((((((((((((((((((((((((((((((((((((((((((`cu_customermaster` `cliente` join `ad_identificationtype` `tipo_id` on((`cliente`.`identificationtype` = `tipo_id`.`ad_identificationtype_id`))) left join `c_bpartner_location` `cbl` on((`cliente`.`branch` = `cbl`.`c_bpartner_location_id`))) left join `c_bpartner_location` `cbl2` on((`cbl`.`ad_org_location_id` = `cbl2`.`c_bpartner_location_id`))) left join `cu_address` `telefono` on(((`telefono`.`cu_customermaster_id` = `cliente`.`cu_customermaster_id`) and (`telefono`.`addressclass` = 'TM') and (`telefono`.`is_mainaddress` = 'Y')))) left join `cu_address` `email` on(((`email`.`cu_customermaster_id` = `cliente`.`cu_customermaster_id`) and (`email`.`addressclass` = 'CE') and (`email`.`is_mainaddress` = 'Y')))) left join `adm_coddesc` `genero` on(((`cliente`.`sex` = `genero`.`adm_coddesc_id`) and (`genero`.`adm_codtitle_id` = 100007)))) left join `cu_personal` `persona` on((`cliente`.`cu_customermaster_id` = `persona`.`cu_customermaster_id`))) left join `c_nation` `nacion` on((`persona`.`citizenship` = `nacion`.`c_nation_id`))) left join `cu_coddesc` `dependencia` on((`persona`.`dependents` = `dependencia`.`cu_coddesc_id`))) left join `adm_coddesc` `marital` on((`persona`.`maritalstatus` = `marital`.`adm_coddesc_id`))) left join `cu_coddesc` `estudio` on((`persona`.`academiclevel` = `estudio`.`cu_coddesc_id`))) left join `cu_coddesc` `profe` on((`persona`.`profession_id` = `profe`.`cu_coddesc_id`))) left join `cu_employment` `empresa` on(((`empresa`.`cu_customermaster_id` = `cliente`.`cu_customermaster_id`) and (`empresa`.`is_mainemploy` = 'Y')))) left join `cu_finantial` `financiero` on((`cliente`.`cu_customermaster_id` = `financiero`.`cu_customermaster_id`))) left join `adm_tipo_contrato` `tipo_contrato` on((`empresa`.`contracttype` = `tipo_contrato`.`adm_tipo_contrato_id`))) left join `cu_coddesc` `economia` on((`empresa`.`economicactivity` = `economia`.`cu_coddesc_id`))) left join `cu_coddesc` `cargo` on((`empresa`.`position` = `cargo`.`cu_coddesc_id`))) left join `adm_coddesc` `ocupacion` on((`persona`.`occupation` = `ocupacion`.`adm_coddesc_id`))) left join `vw_rs_datos_personales_parte01_beneficiarios` `beneficiarios` on((`cliente`.`cu_customermaster_id` = `beneficiarios`.`cu_customermaster_id`))) left join `vw_rs_datos_personales_parte02_tipo_vinculo` `cliente_vinculo` on((`cliente`.`cu_customermaster_id` = `cliente_vinculo`.`cu_customermaster_id`))) left join `cu_coddesc` `empleo_estado` on((`empresa`.`employmentlink` = `empleo_estado`.`cu_coddesc_id`))) left join `cu_address` `direccion_comercial` on(((`direccion_comercial`.`cu_customermaster_id` = `cliente`.`cu_customermaster_id`) and (`direccion_comercial`.`addressclass` = 'DF') and (`direccion_comercial`.`addresstype` = 1001709)))) left join `c_city` `ciudad_comercial` on((`direccion_comercial`.`c_city_id` = `ciudad_comercial`.`c_city_id`))) left join `vw_rs_datos_personales_parte03_vinculo` `vinculo` on(((`vinculo`.`cu_customermaster_id` = `cliente`.`cu_customermaster_id`) and (`vinculo`.`cu_codtitle_id` = 10049)))) left join `cu_customerinfo` on((`cliente`.`cu_customermaster_id` = `cu_customerinfo`.`cu_customermaster_id`))) left join `vw_rs_datos_personales_parte09_pagaduria` `pagaduria` on((`pagaduria`.`acuerdo` = `cliente`.`cu_customermaster_id`))) left join `vw_rs_datos_personales_parte08_vinculado` `vinculado` on((`vinculado`.`cu_customermaster_id` = `cliente`.`cu_customermaster_id`))) left join `vw_rs_datos_personales_parte06_usuario_retiro` `usuario_retiro` on((`usuario_retiro`.`cu_customermaster_id` = `cliente`.`cu_customermaster_id`))) left join `cu_coddesc` `motivo_ret` on(((`cu_customerinfo`.`retirement_reason` = `motivo_ret`.`cu_coddesc_id`) and (`motivo_ret`.`cu_codtitle_id` = 10044) and (`motivo_ret`.`isactive` = 'Y')))) left join `ad_user` `usuario` on((`cliente`.`updatedby` = `usuario`.`ad_user_id`))) left join `cu_multipleselection` `usoDatos` on(((`cliente`.`cu_customermaster_id` = `usoDatos`.`cu_customermaster_id`) and (`usoDatos`.`value` = 'LEY-1581-2012')))) left join `cu_coddesc` `vivienda` on((`persona`.`housingtype` = `vivienda`.`cu_coddesc_id`))) left join `c_city` `ciunac` on((`persona`.`c_city_id` = `ciunac`.`c_city_id`))) left join `c_region` `regnac` on((`persona`.`c_region_id` = `regnac`.`c_region_id`))) left join `c_country` `ccy` on((`persona`.`c_country_id` = `ccy`.`c_country_id`))) left join `cu_employment` `cue` on(((`cliente`.`cu_customermaster_id` = `cue`.`cu_customermaster_id`) and (`cue`.`is_mainemploy` = 'Y')))) left join `cu_legalrep` `curep` on((`cliente`.`cu_customermaster_id` = `curep`.`companyrep`))) left join `c_region` `ccrep` on((`curep`.`c_region_id` = `ccrep`.`c_region_id`))) left join `c_city` `cctrep` on((`curep`.`c_city_id` = `cctrep`.`c_city_id`))) left join `cu_customeraccounts` `cccus` on((`cliente`.`cu_customermaster_id` = `cccus`.`cu_customermaster_id`))) left join `cu_company` `cucom` on((`cliente`.`cu_customermaster_id` = `cucom`.`cu_customermaster_id`))) left join `cu_coddesc` `cucod` on(((`cucom`.`sectorcompany` = `cucod`.`cu_coddesc_id`) and (`cucod`.`cu_codtitle_id` = 10023)))) left join `cu_coddesc` `cucae` on(((`cucom`.`economicactivity` = `cucae`.`cu_coddesc_id`) and (`cucae`.`cu_codtitle_id` = 100006)))) left join `c_region` `ccrcuen` on((`cccus`.`c_region_id` = `ccrcuen`.`c_region_id`))) left join `c_city` `cctcuen` on((`cccus`.`c_city_id` = `cctcuen`.`c_city_id`))) left join `c_country` `cc` on((`financiero`.`country_foreign` = `cc`.`c_country_id`))) left join `c_currency` `ccr` on((`financiero`.`currency_foreign` = `ccr`.`c_currency_id`)))", engine )

In [24]:
datos_personales['Nro_Identificacion'] = pd.to_numeric(datos_personales['Nro_Identificacion'], errors = 'coerce')

In [10]:
#Reasignar columnas en el orden de la plantilla
plantilla = reporte_sistema[['Convenio','Nit cc', 'Nombre Cliente', 'Apellidos Cliente', 'Celular', 'Email', 'Direccion', 'Ciudad', 'Departamento', 'Nro. Credito', 'Sucursal de desembolso', 'Mes de reporte', 'Valor del credito', 'Fecha de desembolso', 'Fecha vencimiento', 'Linea de Credito', 'Cuota', 'Plazo', 'Tasa interes', 'Periodo Gracia', 'Amortizacion capital', 'Amortizacion periodo', 'Amortizacion Modalidad', 'Porcentaje Comision', 'Valor Comision', 'Valor IVA comision', 'Valor Total Comision']]

In [11]:
#Insertar columnas que están en la plantilla y no están en el reporte que genera el sistema
plantilla.insert(1, 'Tipo de identificación', value = int)
plantilla.insert(3, 'Género del cliente', value = int)
plantilla.insert(4, 'Edad', value = int)
plantilla.insert(6, 'Teléfono del cliente', value = int)
plantilla.insert(12, 'CIUU', value = int)
plantilla.insert(13, 'Numero de pagare', value = int)
plantilla.insert(21, 'Portafolio', value = int)
plantilla.insert(22, 'Prenda', value = int)
plantilla.insert(23, 'hipoteca', value = int)
plantilla.insert(26, 'tasa interes nominal anual', value = float)
plantilla.insert(37, 'Identificación codeudor C.C / DNI / NIT / RUC', value = int)
plantilla.insert(38, 'Codeudor nombre Persona Natural / Jurídica', value = str)
plantilla.insert(39, 'Codeudor apellidos', value = str)
plantilla.insert(40, 'Codeudor Teléfono móvil', value = int)
plantilla.insert(41, 'Codeudor dirección', value = str)
plantilla.insert(42, 'Codeudor Provincia/Ciudad/Municipio', value = str)
plantilla.insert(43, 'Codeudor Departamento / Región', value = str)
plantilla.insert(44, 'Observaciones', value = str)

In [12]:
plantilla.columns

Index(['Convenio', 'Tipo de identificación', 'Nit cc', 'Género del cliente',
       'Edad', 'Nombre Cliente', 'Teléfono del cliente', 'Apellidos Cliente',
       'Celular', 'Email', 'Direccion', 'Ciudad', 'CIUU', 'Numero de pagare',
       'Departamento', 'Nro. Credito', 'Sucursal de desembolso',
       'Mes de reporte', 'Valor del credito', 'Fecha de desembolso',
       'Fecha vencimiento', 'Portafolio', 'Prenda', 'hipoteca',
       'Linea de Credito', 'Cuota', 'tasa interes nominal anual', 'Plazo',
       'Tasa interes', 'Periodo Gracia', 'Amortizacion capital',
       'Amortizacion periodo', 'Amortizacion Modalidad', 'Porcentaje Comision',
       'Valor Comision', 'Valor IVA comision', 'Valor Total Comision',
       'Identificación codeudor C.C / DNI / NIT / RUC',
       'Codeudor nombre Persona Natural / Jurídica', 'Codeudor apellidos',
       'Codeudor Teléfono móvil', 'Codeudor dirección',
       'Codeudor Provincia/Ciudad/Municipio', 'Codeudor Departamento / Región',
       'Observaciones'],
      dtype='object')

In [13]:
# Se realiza el cambio de los nombres de las columnas para que estos coincidan con el formato descargado en la pagina donde se carga la relacion de las garantias
plantilla = plantilla.rename(columns={"Convenio":"Numero de Convenio",
                          "Nit cc":"Identificación del cliente (C.C / DNI / NIT / RUC)", 
                          "Nombre Cliente": "Nombre Persona Natural / Jurídica", 
                          "Apellidos Cliente": "Apellidos Persona Natural / Jurídica", 
                          "Celular": "Celular del cliente", 
                          "Email": "Correo electrónico cliente", 
                          "Direccion": "Dirección del cliente", 
                          "Ciudad": "Ciudad/Provincia/Municipio", 
                          "Departamento": "Departamento/Región", 
                          "Nro. Credito": "Número/Referencia del crédito", 
                          "Mes de reporte": "Mes de desembolso", 
                          "Valor del credito": "Valor/ Importe del crédito", 
                          "Linea de Credito": "Tipo_crédito", 
                          "Cuota": "Valor/ Importe cuota", 
                          "Tasa interes": "Tasa interés efectiva anual", 
                          "Amortizacion capital": "Tipo de cuota",
                          "Amortizacion periodo": "Amortización cuota", 
                          "Amortizacion Modalidad": "Tipo de amortización de la cuota", 
                          "Valor Comision": "Valor/Importe comisión", 
                          "Valor IVA comision": "Valor/Importe Impuesto de comision", 
                          "Valor Total Comision": "Valor/Importe Total comisión"})

In [61]:
plantilla.columns

Index(['Numero de Convenio', 'Tipo de identificación',
       'Identificación del cliente (C.C / DNI / NIT / RUC)',
       'Género del cliente', 'Edad', 'Nombre Persona Natural / Jurídica',
       'Teléfono del cliente', 'Apellidos Persona Natural / Jurídica',
       'Celular del cliente', 'Correo electrónico cliente',
       'Dirección del cliente', 'Ciudad/Provincia/Municipio', 'CIUU',
       'Numero de pagare', 'Departamento/Región',
       'Número/Referencia del crédito', 'Sucursal de desembolso',
       'Mes de desembolso', 'Valor/ Importe del crédito',
       'Fecha de desembolso', 'Fecha vencimiento', 'Portafolio', 'Prenda',
       'hipoteca', 'Tipo_crédito', 'Valor/ Importe cuota',
       'tasa interes nominal anual', 'Plazo', 'Tasa interés efectiva anual',
       'Periodo Gracia', 'Tipo de cuota', 'Amortización cuota',
       'Tipo de amortización de la cuota', 'Porcentaje Comision',
       'Valor/Importe comisión', 'Valor/Importe Impuesto de comision',
       'Valor/Importe Total comisión',
       'Identificación codeudor C.C / DNI / NIT / RUC',
       'Codeudor nombre Persona Natural / Jurídica', 'Codeudor apellidos',
       'Codeudor Teléfono móvil', 'Codeudor dirección',
       'Codeudor Provincia/Ciudad/Municipio', 'Codeudor Departamento / Región',
       'Observaciones'],
      dtype='object')

In [14]:
plantilla

,Numero de Convenio,Tipo de identificación,Identificación del cliente (C.C / DNI / NIT / RUC),Género del cliente,Edad,Nombre Persona Natural / Jurídica,Teléfono del cliente,Apellidos Persona Natural / Jurídica,Celular del cliente,Correo electrónico cliente,...,Valor/Importe Impuesto de comision,Valor/Importe Total comisión,Identificación codeudor C.C / DNI / NIT / RUC,Codeudor nombre Persona Natural / Jurídica,Codeudor apellidos,Codeudor Teléfono móvil,Codeudor dirección,Codeudor Provincia/Ciudad/Municipio,Codeudor Departamento / Región,Observaciones
0,3,<class 'int'>,1088331217,<class 'int'>,<class 'int'>,DIEGO ALEJANDRO,<class 'int'>,RAMIREZ MEJIA,3206682048,alejo.7407@hotmail.com,...,79420,497420,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
1,3,<class 'int'>,15986190,<class 'int'>,<class 'int'>,JOSE NORBERTO,<class 'int'>,BEDOYA JIMENEZ,3218839269,LEYDYBEDOYARODRIGUEZ@GMAIL.COM,...,21660,135660,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
2,3,<class 'int'>,1093228976,<class 'int'>,<class 'int'>,JOHAN,<class 'int'>,GIRALDO MORALES,3116667026,JOHAN-4385@HOTMAIL.COM,...,15884,99484,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
3,3,<class 'int'>,94319621,<class 'int'>,<class 'int'>,PEDRO NEL,<class 'int'>,CALDERON LOPEZ,3156133624,NaN,...,108300,678300,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
4,3,<class 'int'>,1112627598,<class 'int'>,<class 'int'>,JULIAN AUGUSTO,<class 'int'>,GUZMAN GOMEZ,3178661148,NaN,...,61731,386631,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
5,3,<class 'int'>,9738470,<class 'int'>,<class 'int'>,JORGE MARIO,<class 'int'>,AGUIRRE FLOREZ,3105153455,jorgerosoneri7@hotmail.com,...,36100,226100,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
6,3,<class 'int'>,41948444,<class 'int'>,<class 'int'>,VERONICA MARIA,<class 'int'>,RONCANCIO HOYOS,3137031134,celeste.219@hotmail.com,...,49818,312018,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
7,3,<class 'int'>,31396584,<class 'int'>,<class 'int'>,ELIZABETH,<class 'int'>,REINA CASTAÑO,3146671814,NaN,...,43320,271320,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
8,3,<class 'int'>,98381102,<class 'int'>,<class 'int'>,FABIO ALDEMAR,<class 'int'>,GUANCHA CEBALLOS,3136240317,faguac72@hotmail.com,...,72200,452200,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
9,3,<class 'int'>,1113782785,<class 'int'>,<class 'int'>,LINA MERCEDES,<class 'int'>,YEPES ARDILA,3182812925,linay1703@gmail.com,...,15162,94962,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
10,3,<class 'int'>,9730985,<class 'int'>,<class 'int'>,RICARDO,<class 'int'>,GRISALES LONDONO,3104205057,rigrilo@gmail.com,...,72200,452200,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
11,3,<class 'int'>,25085858,<class 'int'>,<class 'int'>,MARTA NELGIBIA,<class 'int'>,GIRALDO GIRALDO,3235086500,daniela5a723@hotmail.com,...,45486,284886,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
12,3,<class 'int'>,1093223865,<class 'int'>,<class 'int'>,DANIEL,<class 'int'>,CARMONA SOTO,3105136799,dcarmonasoto07@gmail.com,...,68590,429590,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
13,3,<class 'int'>,1088278765,<class 'int'>,<class 'int'>,DIEGO MAURICIO,<class 'int'>,ARBOLEDA MARULANDA,3234092515,dmapiti52@hotmail.com,...,14440,90440,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
14,3,<class 'int'>,1088021697,<class 'int'>,<class 'int'>,JORGE LIBARDO,<class 'int'>,MONTOYA RODRIGUEZ,3215488037,jorgemontoya0316@gmail.com,...,54150,339150,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
15,3,<class 'int'>,1097038972,<class 'int'>,<class 'int'>,LINA MARIA,<class 'int'>,ANDRADE CASTAÑO,3106217242,NaN,...,25270,158270,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
16,3,<class 'int'>,1112625509,<class 'int'>,<class 'int'>,ALEX HERNAN,<class 'int'>,RIVERA HERNANDEZ,3159261281,alexrivera92.44@gmail.com,...,41154,257754,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
17,3,<class 'int'>,1006332720,<class 'int'>,<class 'int'>,LUIS ANGEL,<class 'int'>,MEDINA GUARIN,3104613014,NaN,...,45486,284886,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
18,3,<class 'int'>,1088020863,<class 'int'>,<class 'int'>,DANIELA,<class 'int'>,VALERO MORA,3185654694,danielavaleromora@gmail.com,...,25270,158270,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
19,3,<class 'int'>,17225194,<class 'int'>,<class 'int'>,JOSE YESI,<class 'int'>,JARAMILLO MARIN,3218682044,jesidjaramillo775@gmail.com,...,28880,180880,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
20,3,<class 'int'>,1115076743,<class 'int'>,<class 'int'>,FRANCY JULIETH,<class 'int'>,CALLE VILLEGAS,3193151007,julieth.calle10@gmail.com,...,15162,94962,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
21,3,<class 'int'>,94275851,<class 'int'>,<class 'int'>,CRISTIAN PAUL,<class 'int'>,VELASQUEZ,3207526237,cristianjkvrlasquez21@gmail.com,...,59204,370804,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
22,3,<class 'int'>,18417213,<class 'int'>,<class 'int'>,RUBEN DARIO,<class 'int'>,GONZALEZ CARDONA,3113205217,golzalezcardonar9@gmail.com,...,19855,124355,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
23,3,<class 'int'>,1114389648,<class 'int'>,<class 'int'>,ANA MILENA,<class 'int'>,MUÑOZ VALENCIA,3128386900,anita4224@hotmail.com,...,34656,217056,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
24,3,<class 'int'>,1094939215,<class 'int'>,<class 'int'>,LUIS FERNANDO,<class 'int'>,AGUDELO MONTOYA,3138692903,NaN,...,57760,361760,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
25,3,<class 'int'>,10196940,<class 'int'>,<class 'int'>,JUAN CARLOS,<class 'int'>,FRANCO CANO,3205227735,NaN,...,43320,271320,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
26,3,<class 'int'>,1088309845,<class 'int'>,<class 'int'>,VICTOR ALEJANDRO,<class 'int'>,CARDONA RAMIREZ,3004109602,alejochanti@gmail.com,...,158840,994840,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
27,3,<class 'int'>,1062328210,<class 'int'>,<class 'int'>,ANDRES FELIPE,<class 'int'>,RENGIFO BADOS,3136149221,ANDRESBADOSCI@GMAIL.COM,...,22382,140182,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
28,3,<class 'int'>,1074888313,<class 'int'>,<class 'int'>,WILLIAM SALVADOR,<class 'int'>,VILLAMIL BELLO,3143306899,willyad@hotmail.es,...,18050,113050,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
29,3,<class 'int'>,1116235806,<class 'int'>,<class 'int'>,GIOVANY,<class 'int'>,MONTOYA LLANOS,3154229573,NaN,...,21660,135660,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
30,3,<class 'int'>,10065672,<class 'int'>,<class 'int'>,SERGIO,<class 'int'>,MARIN OCAMPO,3136970331,sergiomarinocampo727@gmail.com,...,46930,293930,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
31,3,<class 'int'>,42134480,<class 'int'>,<class 'int'>,JACKELINE,<class 'int'>,BEDOYA SALAZAR,3175244403,bedoyapekitas@gmail.com,...,83030,520030,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
32,3,<class 'int'>,16698049,<class 'int'>,<class 'int'>,ROMULO,<class 'int'>,CUELLAR ALFARO,3158643545,romulocuellar@hotmail.com,...,43320,271320,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
33,3,<class 'int'>,6358716,<class 'int'>,<class 'int'>,WILSON HERIBER,<class 'int'>,CASTAÑO RAMIREZ,3127584893,NaN,...,10108,63308,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
34,3,<class 'int'>,29285574,<class 'int'>,<class 'int'>,MONICA,<class 'int'>,CUBIDES ECHEVERRY,3128147605,monica_cubides6@hotmail.com,...,36100,226100,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
35,3,<class 'int'>,1112629390,<class 'int'>,<class 'int'>,MAURO ALEXIS,<class 'int'>,RAMIREZ DURAN,3116691217,NaN,...,21660,135660,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
36,3,<class 'int'>,1003535035,<class 'int'>,<class 'int'>,ANGIE TATIANA,<class 'int'>,GUERRERO BOHORQUEZ,3507370894,GUERREROANGIE3016@GMAIL.COM,...,14440,90440,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
37,3,<class 'int'>,1115071676,<class 'int'>,<class 'int'>,DIANA MARCELA,<class 'int'>,VELEZ GARZON,3164588794,damave01@hotmail.com,...,43320,271320,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
38,3,<class 'int'>,1094953570,<class 'int'>,<class 'int'>,LAURA FERNANDA,<class 'int'>,OSORIO CASTAÑEDA,3195350661,nenaosorio16@hotmail.com,...,28880,180880,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
39,3,<class 'int'>,29771671,<class 'int'>,<class 'int'>,BETTY,<class 'int'>,AGUDELO,3128830799,NaN,...,20216,126616,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
40,3,<class 'int'>,1053792130,<class 'int'>,<class 'int'>,JACKELINE,<class 'int'>,GARZON DOMINGUEZ,3138732818,jacgarzon@hotmail.com,...,28880,180880,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
41,3,<class 'int'>,1112933220,<class 'int'>,<class 'int'>,CARLOS ANDRES,<class 'int'>,GIRALDO ROJAS,3128830799,malak1693@gmail.com,...,29602,185402,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
42,3,<class 'int'>,41949163,<class 'int'>,<class 'int'>,LINA MARÍA,<class 'int'>,YARA MARTINEZ,3103460087,linamaria.80@hotmail.com,...,33212,208012,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
43,3,<class 'int'>,1114091458,<class 'int'>,<class 'int'>,GUSTAVO ADOLFO,<class 'int'>,GRISALES CANO,3154549262,guxtavo-0912@hotmail.com,...,42598,266798,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
44,3,<class 'int'>,16688459,<class 'int'>,<class 'int'>,ROLANDO,<class 'int'>,ZAPATA,3104565231,rolandozapata63@hotmail.com,...,72200,452200,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
45,3,<class 'int'>,66753398,<class 'int'>,<class 'int'>,ANGELICA MARIA,<class 'int'>,CARDONA MONTOYA,3128830799,anyimmon-1@gmail.com,...,45847,287147,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
46,3,<class 'int'>,1053787241,<class 'int'>,<class 'int'>,LUISA FERNANDA,<class 'int'>,PALACIO HENAO,3106262206,luisapalacio@hotmail.com,...,32490,203490,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
47,3,<class 'int'>,1112788983,<class 'int'>,<class 'int'>,MANUELA,<class 'int'>,IZQUIERDO SALAZAR,3104691640,MANU_ELA_96@HOTMAIL.COM,...,43320,271320,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
48,3,<class 'int'>,1112101980,<class 'int'>,<class 'int'>,ANDREA JULIETH,<class 'int'>,BARRANTES MONTES,3137478384,andrejuli2690@gmail.com,...,8664,54264,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
49,3,<class 'int'>,1149461450,<class 'int'>,<class 'int'>,ALEJANDRO JOSE,<class 'int'>,RIVAS UZCATEGUI,3103116887,alejandro.ru2110@gmail.com,...,36100,226100,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
50,3,<class 'int'>,1094945767,<class 'int'>,<class 'int'>,JUAN CARLOS,<class 'int'>,OROZCO PIAMBA,3104334982,juanc-orozco@hotmail.com,...,21660,135660,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
51,3,<class 'int'>,29285534,<class 'int'>,<class 'int'>,YUVIRY,<class 'int'>,ALVAREZ VALLEJO,3166194714,luchiyisell2018@gmail.com,...,38266,239666,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
52,3,<class 'int'>,31331487,<class 'int'>,<class 'int'>,CLAUDIA MILENA,<class 'int'>,BEDOYA ARIAS,3136607605,CLAU_BE12@OUTLOOK.COM,...,29602,185402,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
53,3,<class 'int'>,1088033059,<class 'int'>,<class 'int'>,STEPHANY,<class 'int'>,MONCADA RIVERA,3007435259,nis_1998@hotmail.com,...,36100,226100,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
54,3,<class 'int'>,19497379,<class 'int'>,<class 'int'>,ALVARO,<class 'int'>,SOTO GONZALEZ,3214817587,NaN,...,21660,135660,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
55,3,<class 'int'>,21481908,<class 'int'>,<class 'int'>,BLANCA ELEIDY,<class 'int'>,GIRALDO GOMEZ,3163227488,calzamundocartago@gmail.com,...,43320,271320,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
56,3,<class 'int'>,1112624466,<class 'int'>,<class 'int'>,GUSTAVO ADOLFO,<class 'int'>,AVENDAÑO PINEDA,3145143835,avendano2791@gmail.com,...,7942,49742,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
57,3,<class 'int'>,31309799,<class 'int'>,<class 'int'>,MARIA ISABEL,<class 'int'>,MONTOYA GONZALEZ,3233153595,misabelmontoya@hotmail.com,...,21660,135660,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>
58,3,<class 'int'>,1053847490,<class 'int'>,<class 'int'>,KARENN,<class 'int'>,ZULUAGA PEREZ,3202912807,kazuluaga8@hotmail.com,...,18050,113050,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>

In [25]:
plantilla_datos = plantilla.merge(datos_personales, how = 'inner', left_on = 'Identificación del cliente (C.C / DNI / NIT / RUC)', right_on = 'Nro_Identificacion')

In [26]:
plantilla_datos

,Numero de Convenio,Tipo de identificación,Identificación del cliente (C.C / DNI / NIT / RUC),Género del cliente,Edad_x,Nombre Persona Natural / Jurídica,Teléfono del cliente,Apellidos Persona Natural / Jurídica,Celular del cliente,Correo electrónico cliente,...,Observaciones,Tipo_Identificacion,Nro_Identificacion,Genero,Fecha_Nacimiento,Edad_y,Telefono_Residencia,Codigo_CIIUU_Ciudad_Residencia,Codigo_CIIUU_Ciudad_Comercial,Codigo_CIIU_Asociado
0,3,<class 'int'>,1088331217,<class 'int'>,<class 'int'>,DIEGO ALEJANDRO,<class 'int'>,RAMIREZ MEJIA,3206682048,alejo.7407@hotmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.088331e+09,Masculino,1995-11-15 00:00:00,26.0,,66-66001,,0010
1,3,<class 'int'>,15986190,<class 'int'>,<class 'int'>,JOSE NORBERTO,<class 'int'>,BEDOYA JIMENEZ,3218839269,LEYDYBEDOYARODRIGUEZ@GMAIL.COM,...,<class 'str'>,CEDULA DE CIUDADANIA,1.598619e+07,Masculino,1963-01-20 00:00:00,58.0,,76-76001,,4631
2,3,<class 'int'>,1093228976,<class 'int'>,<class 'int'>,JOHAN,<class 'int'>,GIRALDO MORALES,3116667026,JOHAN-4385@HOTMAIL.COM,...,<class 'str'>,CEDULA DE CIUDADANIA,1.093229e+09,Masculino,1998-03-04 00:00:00,23.0,,66-66682,,0010
3,3,<class 'int'>,94319621,<class 'int'>,<class 'int'>,PEDRO NEL,<class 'int'>,CALDERON LOPEZ,3156133624,NaN,...,<class 'str'>,CEDULA DE CIUDADANIA,9.431962e+07,Masculino,1973-08-21 00:00:00,48.0,,76-76001,,0090
4,3,<class 'int'>,1112627598,<class 'int'>,<class 'int'>,JULIAN AUGUSTO,<class 'int'>,GUZMAN GOMEZ,3178661148,NaN,...,<class 'str'>,CEDULA DE CIUDADANIA,1.112628e+09,Masculino,1994-08-01 00:00:00,27.0,,76-76400,,0010
5,3,<class 'int'>,9738470,<class 'int'>,<class 'int'>,JORGE MARIO,<class 'int'>,AGUIRRE FLOREZ,3105153455,jorgerosoneri7@hotmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,9.738470e+06,Masculino,1984-01-09 00:00:00,37.0,7350967,63-63001,63-63001,0010
6,3,<class 'int'>,41948444,<class 'int'>,<class 'int'>,VERONICA MARIA,<class 'int'>,RONCANCIO HOYOS,3137031134,celeste.219@hotmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,4.194844e+07,Femenino,1980-12-31 00:00:00,41.0,,63-63001,,6810
7,3,<class 'int'>,31396584,<class 'int'>,<class 'int'>,ELIZABETH,<class 'int'>,REINA CASTAÑO,3146671814,NaN,...,<class 'str'>,CEDULA DE CIUDADANIA,3.139658e+07,Femenino,1957-11-09 00:00:00,64.0,,76-76147,,0081
8,3,<class 'int'>,98381102,<class 'int'>,<class 'int'>,FABIO ALDEMAR,<class 'int'>,GUANCHA CEBALLOS,3136240317,faguac72@hotmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,9.838110e+07,Masculino,1972-02-22 00:00:00,49.0,,63-63001,,0081
9,3,<class 'int'>,1113782785,<class 'int'>,<class 'int'>,LINA MERCEDES,<class 'int'>,YEPES ARDILA,3182812925,linay1703@gmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.113783e+09,Femenino,1988-12-06 00:00:00,33.0,,76-76622,,0010
10,3,<class 'int'>,9730985,<class 'int'>,<class 'int'>,RICARDO,<class 'int'>,GRISALES LONDONO,3104205057,rigrilo@gmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,9.730985e+06,Masculino,1978-12-30 00:00:00,43.0,7453926,63-63001,,9609
11,3,<class 'int'>,25085858,<class 'int'>,<class 'int'>,MARTA NELGIBIA,<class 'int'>,GIRALDO GIRALDO,3235086500,daniela5a723@hotmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,2.508586e+07,Femenino,1958-02-01 00:00:00,63.0,3120697,66-66001,,0081
12,3,<class 'int'>,1093223865,<class 'int'>,<class 'int'>,DANIEL,<class 'int'>,CARMONA SOTO,3105136799,dcarmonasoto07@gmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.093224e+09,Masculino,1994-05-16 00:00:00,27.0,,66-66682,,6621
13,3,<class 'int'>,1088278765,<class 'int'>,<class 'int'>,DIEGO MAURICIO,<class 'int'>,ARBOLEDA MARULANDA,3234092515,dmapiti52@hotmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.088279e+09,Masculino,1990-05-19 00:00:00,31.0,,66-66001,,0010
14,3,<class 'int'>,1088021697,<class 'int'>,<class 'int'>,JORGE LIBARDO,<class 'int'>,MONTOYA RODRIGUEZ,3215488037,jorgemontoya0316@gmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.088022e+09,Masculino,1995-03-16 00:00:00,26.0,,66-66170,,0010
15,3,<class 'int'>,1097038972,<class 'int'>,<class 'int'>,LINA MARIA,<class 'int'>,ANDRADE CASTAÑO,3106217242,NaN,...,<class 'str'>,CEDULA DE CIUDADANIA,1.097039e+09,Femenino,1995-08-29 00:00:00,26.0,,63-63594,,0010
16,3,<class 'int'>,1112625509,<class 'int'>,<class 'int'>,ALEX HERNAN,<class 'int'>,RIVERA HERNANDEZ,3159261281,alexrivera92.44@gmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.112626e+09,Masculino,1992-05-26 00:00:00,29.0,,76-76400,,0010
17,3,<class 'int'>,1006332720,<class 'int'>,<class 'int'>,LUIS ANGEL,<class 'int'>,MEDINA GUARIN,3104613014,NaN,...,<class 'str'>,CEDULA DE CIUDADANIA,1.006333e+09,Masculino,1997-06-23 00:00:00,24.0,,76-76606,,0010
18,3,<class 'int'>,1088020863,<class 'int'>,<class 'int'>,DANIELA,<class 'int'>,VALERO MORA,3185654694,danielavaleromora@gmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.088021e+09,Femenino,1994-12-29 00:00:00,27.0,3425724,66-66170,,0010
19,3,<class 'int'>,17225194,<class 'int'>,<class 'int'>,JOSE YESI,<class 'int'>,JARAMILLO MARIN,3218682044,jesidjaramillo775@gmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.722519e+07,Masculino,1976-02-21 00:00:00,45.0,0,66-66001,,0010
20,3,<class 'int'>,1115076743,<class 'int'>,<class 'int'>,FRANCY JULIETH,<class 'int'>,CALLE VILLEGAS,3193151007,julieth.calle10@gmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.115077e+09,Femenino,1992-01-10 00:00:00,29.0,,76-76111,,0010
21,3,<class 'int'>,94275851,<class 'int'>,<class 'int'>,CRISTIAN PAUL,<class 'int'>,VELASQUEZ,3207526237,cristianjkvrlasquez21@gmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,9.427585e+07,Masculino,1980-08-22 00:00:00,41.0,,76-76400,,0010
22,3,<class 'int'>,18417213,<class 'int'>,<class 'int'>,RUBEN DARIO,<class 'int'>,GONZALEZ CARDONA,3113205217,golzalezcardonar9@gmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.841721e+07,Masculino,1977-01-29 00:00:00,44.0,,63-63594,,0010
23,3,<class 'int'>,1114389648,<class 'int'>,<class 'int'>,ANA MILENA,<class 'int'>,MUÑOZ VALENCIA,3128386900,anita4224@hotmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.114390e+09,Femenino,1994-06-14 00:00:00,27.0,,76-76606,,9602
24,3,<class 'int'>,1094939215,<class 'int'>,<class 'int'>,LUIS FERNANDO,<class 'int'>,AGUDELO MONTOYA,3138692903,NaN,...,<class 'str'>,CEDULA DE CIUDADANIA,1.094939e+09,Masculino,1993-12-23 00:00:00,28.0,,63-63001,,4923
25,3,<class 'int'>,10196940,<class 'int'>,<class 'int'>,JUAN CARLOS,<class 'int'>,FRANCO CANO,3205227735,NaN,...,<class 'str'>,CEDULA DE CIUDADANIA,1.019694e+07,Masculino,1967-06-12 00:00:00,54.0,,76-76041,76-76041,0010
26,3,<class 'int'>,1088309845,<class 'int'>,<class 'int'>,VICTOR ALEJANDRO,<class 'int'>,CARDONA RAMIREZ,3004109602,alejochanti@gmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.088310e+09,Masculino,2011-07-13 00:00:00,10.0,,66-66170,,0010
27,3,<class 'int'>,1062328210,<class 'int'>,<class 'int'>,ANDRES FELIPE,<class 'int'>,RENGIFO BADOS,3136149221,ANDRESBADOSCI@GMAIL.COM,...,<class 'str'>,CEDULA DE CIUDADANIA,1.062328e+09,Masculino,1997-10-06 00:00:00,24.0,,76-76001,76-76001,1081
28,3,<class 'int'>,1074888313,<class 'int'>,<class 'int'>,WILLIAM SALVADOR,<class 'int'>,VILLAMIL BELLO,3143306899,willyad@hotmail.es,...,<class 'str'>,CEDULA DE CIUDADANIA,1.074888e+09,Masculino,1990-04-01 00:00:00,31.0,,25-25781,25-25486,0010
29,3,<class 'int'>,1116235806,<class 'int'>,<class 'int'>,GIOVANY,<class 'int'>,MONTOYA LLANOS,3154229573,NaN,...,<class 'str'>,CEDULA DE CIUDADANIA,1.116236e+09,Masculino,1986-09-29 00:00:00,35.0,2311447,76-76834,,0010
30,3,<class 'int'>,10065672,<class 'int'>,<class 'int'>,SERGIO,<class 'int'>,MARIN OCAMPO,3136970331,sergiomarinocampo727@gmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.006567e+07,Masculino,1949-07-27 00:00:00,72.0,3266333,66-66001,,6810
31,3,<class 'int'>,42134480,<class 'int'>,<class 'int'>,JACKELINE,<class 'int'>,BEDOYA SALAZAR,3175244403,bedoyapekitas@gmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,4.213448e+07,Femenino,1978-03-13 00:00:00,43.0,,66-66170,,6810
32,3,<class 'int'>,16698049,<class 'int'>,<class 'int'>,ROMULO,<class 'int'>,CUELLAR ALFARO,3158643545,romulocuellar@hotmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.669805e+07,Masculino,1964-06-17 00:00:00,57.0,,76-76001,,0010
33,3,<class 'int'>,6358716,<class 'int'>,<class 'int'>,WILSON HERIBER,<class 'int'>,CASTAÑO RAMIREZ,3127584893,NaN,...,<class 'str'>,CEDULA DE CIUDADANIA,6.358716e+06,Masculino,1967-05-07 00:00:00,54.0,,76-76400,,0010
34,3,<class 'int'>,29285574,<class 'int'>,<class 'int'>,MONICA,<class 'int'>,CUBIDES ECHEVERRY,3128147605,monica_cubides6@hotmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,2.928557e+07,Femenino,1983-02-06 00:00:00,38.0,,76-76111,,0010
35,3,<class 'int'>,1112629390,<class 'int'>,<class 'int'>,MAURO ALEXIS,<class 'int'>,RAMIREZ DURAN,3116691217,NaN,...,<class 'str'>,CEDULA DE CIUDADANIA,1.112629e+09,Masculino,1996-01-30 00:00:00,25.0,,76-76400,,0010
36,3,<class 'int'>,1003535035,<class 'int'>,<class 'int'>,ANGIE TATIANA,<class 'int'>,GUERRERO BOHORQUEZ,3507370894,GUERREROANGIE3016@GMAIL.COM,...,<class 'str'>,CEDULA DE CIUDADANIA,1.003535e+09,Femenino,2001-04-04 00:00:00,20.0,3507370894,25-25473,,0010
37,3,<class 'int'>,1115071676,<class 'int'>,<class 'int'>,DIANA MARCELA,<class 'int'>,VELEZ GARZON,3164588794,damave01@hotmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.115072e+09,Femenino,1989-10-01 00:00:00,32.0,,76-76111,,0010
38,3,<class 'int'>,1094953570,<class 'int'>,<class 'int'>,LAURA FERNANDA,<class 'int'>,OSORIO CASTAÑEDA,3195350661,nenaosorio16@hotmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.094954e+09,Femenino,1995-12-16 00:00:00,26.0,,63-63001,63-63001,0010
39,3,<class 'int'>,29771671,<class 'int'>,<class 'int'>,BETTY,<class 'int'>,AGUDELO,3128830799,NaN,...,<class 'str'>,CEDULA DE CIUDADANIA,2.977167e+07,Femenino,1959-10-06 00:00:00,62.0,,76-76622,,0081
40,3,<class 'int'>,1053792130,<class 'int'>,<class 'int'>,JACKELINE,<class 'int'>,GARZON DOMINGUEZ,3138732818,jacgarzon@hotmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.053792e+09,Femenino,1989-01-06 00:00:00,32.0,3138732818,17-17174,,0010
41,3,<class 'int'>,1112933220,<class 'int'>,<class 'int'>,CARLOS ANDRES,<class 'int'>,GIRALDO ROJAS,3128830799,malak1693@gmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.112933e+09,Masculino,1993-12-16 00:00:00,28.0,,76-76250,,0010
42,3,<class 'int'>,41949163,<class 'int'>,<class 'int'>,LINA MARÍA,<class 'int'>,YARA MARTINEZ,3103460087,linamaria.80@hotmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,4.194916e+07,Femenino,1980-10-07 00:00:00,41.0,,63-63001,63-63001,0010
43,3,<class 'int'>,1114091458,<class 'int'>,<class 'int'>,GUSTAVO ADOLFO,<class 'int'>,GRISALES CANO,3154549262,guxtavo-0912@hotmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.114091e+09,Masculino,1990-09-12 00:00:00,31.0,,63-63190,63-63190,0010
44,3,<class 'int'>,16688459,<class 'int'>,<class 'int'>,ROLANDO,<class 'int'>,ZAPATA,3104565231,rolandozapata63@hotmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.668846e+07,Masculino,1963-04-07 00:00:00,58.0,,76-76520,52-52001,0081
45,3,<class 'int'>,66753398,<class 'int'>,<class 'int'>,ANGELICA MARIA,<class 'int'>,CARDONA MONTOYA,3128830799,anyimmon-1@gmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,6.675340e+07,Femenino,1979-11-08 00:00:00,42.0,,76-76400,,0010
46,3,<class 'int'>,1053787241,<class 'int'>,<class 'int'>,LUISA FERNANDA,<class 'int'>,PALACIO HENAO,3106262206,luisapalacio@hotmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.053787e+09,Femenino,1988-04-26 00:00:00,33.0,,66-66682,,0010
47,3,<class 'int'>,1112788983,<class 'int'>,<class 'int'>,MANUELA,<class 'int'>,IZQUIERDO SALAZAR,3104691640,MANU_ELA_96@HOTMAIL.COM,...,<class 'str'>,CEDULA DE CIUDADANIA,1.112789e+09,Femenino,1996-12-27 00:00:00,25.0,,76-76147,76-76147,0010
48,3,<class 'int'>,1112101980,<class 'int'>,<class 'int'>,ANDREA JULIETH,<class 'int'>,BARRANTES MONTES,3137478384,andrejuli2690@gmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.112102e+09,Femenino,1990-06-02 00:00:00,31.0,,63-63130,63-63190,0010
49,3,<class 'int'>,1149461450,<class 'int'>,<class 'int'>,ALEJANDRO JOSE,<class 'int'>,RIVAS UZCATEGUI,3103116887,alejandro.ru2110@gmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.149461e+09,Masculino,1992-10-21 00:00:00,29.0,,25-25899,25-25899,0010
50,3,<class 'int'>,1094945767,<class 'int'>,<class 'int'>,JUAN CARLOS,<class 'int'>,OROZCO PIAMBA,3104334982,juanc-orozco@hotmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.094946e+09,Masculino,1994-11-10 00:00:00,27.0,,63-63001,,0010
51,3,<class 'int'>,29285534,<class 'int'>,<class 'int'>,YUVIRY,<class 'int'>,ALVAREZ VALLEJO,3166194714,luchiyisell2018@gmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,2.928553e+07,Femenino,1982-01-10 00:00:00,39.0,,76-76111,,7721
52,3,<class 'int'>,31331487,<class 'int'>,<class 'int'>,CLAUDIA MILENA,<class 'int'>,BEDOYA ARIAS,3136607605,CLAU_BE12@OUTLOOK.COM,...,<class 'str'>,CEDULA DE CIUDADANIA,3.133149e+07,Femenino,1984-02-27 00:00:00,37.0,,76-76400,,0010
53,3,<class 'int'>,1088033059,<class 'int'>,<class 'int'>,STEPHANY,<class 'int'>,MONCADA RIVERA,3007435259,nis_1998@hotmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.088033e+09,Femenino,1998-02-01 00:00:00,23.0,,66-66170,,0010
54,3,<class 'int'>,19497379,<class 'int'>,<class 'int'>,ALVARO,<class 'int'>,SOTO GONZALEZ,3214817587,NaN,...,<class 'str'>,CEDULA DE CIUDADANIA,1.949738e+07,Masculino,1958-01-13 00:00:00,63.0,3214817587,25-25473,,0081
55,3,<class 'int'>,21481908,<class 'int'>,<class 'int'>,BLANCA ELEIDY,<class 'int'>,GIRALDO GOMEZ,3163227488,calzamundocartago@gmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,2.148191e+07,Femenino,1978-11-11 00:00:00,43.0,,76-76147,76-76147,0010
56,3,<class 'int'>,1112624466,<class 'int'>,<class 'int'>,GUSTAVO ADOLFO,<class 'int'>,AVENDAÑO PINEDA,3145143835,avendano2791@gmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.112624e+09,Masculino,1991-05-27 00:00:00,30.0,,76-76400,,0010
57,3,<class 'int'>,31309799,<class 'int'>,<class 'int'>,MARIA ISABEL,<class 'int'>,MONTOYA GONZALEZ,3233153595,misabelmontoya@hotmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,3.130980e+07,Femenino,1985-04-07 00:00:00,36.0,,76-76001,,0010
58,3,<class 'int'>,1053847490,<class 'int'>,<class 'int'>,KARENN,<class 'int'>,ZULUAGA PEREZ,3202912807,kazuluaga8@hotmail.com,...,<class 'str'>,CEDULA DE CIUDADANIA,1.053847e+09,Femenino,1996-01-08 00:00:00,25.0,,17-17174,,0010

In [41]:
for i in plantilla.index:
    #categorias del tipo de identificación
    if plantilla_datos.loc[i,'Tipo_Identificacion'] == 'CEDULA DE CIUDADANIA':
        plantilla.loc[i,'Tipo de identificación'] = 1
    else:
        plantilla.loc[i,'Tipo de identificación'] = plantilla_datos.loc[i,'Tipo_Identificacion']
    # categorias del genero
    if plantilla_datos.loc[i, 'Genero'] == 'Masculino':
        plantilla.loc[i, 'Género del cliente'] = 1
    elif plantilla_datos.loc[i, 'Genero'] == 'Femenino':
        plantilla.loc[i, 'Género del cliente'] = 2
    else:
        plantilla.loc[i, 'Género del cliente'] = 3
    #Categorias de la edad 
    if plantilla_datos.loc[i, 'Edad_y'] < 20:
        plantilla.loc[i,'Edad'] = 1
    elif 20 <= plantilla_datos.loc[i,'Edad_y'] <= 29:
        plantilla.loc[i,'Edad'] = 2
    elif 30 <= plantilla_datos.loc[i,'Edad_y'] <= 39:
        plantilla.loc[i,'Edad'] = 3
    elif 40 <= plantilla_datos.loc[i,'Edad_y'] <= 49:
        plantilla.loc[i,'Edad'] = 4
    elif 50 <= plantilla_datos.loc[i,'Edad_y'] <= 59:
        plantilla.loc[i,'Edad'] = 5
    elif plantilla_datos.loc[i, 'Edad_y'] >= 60:
        plantilla.loc[i,'Edad'] = 6
    else: 
        plantilla.loc[i,'Edad'] = 99
    #telefono del cliente
    plantilla.loc[i, 'Teléfono del cliente'] = plantilla.loc[i, 'Celular del cliente']
    #ciudad y departamento de residencia
    plantilla.loc[i,'Departamento/Región'] = plantilla_datos.loc[i,'Codigo_CIIUU_Ciudad_Residencia'][:2]
    plantilla.loc[i,'Ciudad/Provincia/Municipio'] = plantilla_datos.loc[i,'Codigo_CIIUU_Ciudad_Residencia'][3:]
    #CIIU
    plantilla.loc[i,'CIUU'] = plantilla_datos.loc[i,'Codigo_CIIU_Asociado']

In [42]:
plantilla['Edad']

0     2
1     5
2     2
3     4
4     2
5     3
6     4
7     6
8     4
9     3
10    4
11    6
12    2
13    3
14    2
15    2
16    2
17    2
18    2
19    4
20    2
21    4
22    4
23    2
24    2
25    5
26    1
27    2
28    3
29    3
30    6
31    4
32    5
33    5
34    3
35    2
36    2
37    3
38    2
39    6
40    3
41    2
42    4
43    3
44    5
45    4
46    3
47    2
48    3
49    2
50    2
51    3
52    3
53    2
54    6
55    4
56    3
57    3
58    2
Name: Edad, dtype: object